// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContactsColumns holds the columns for the "contacts" table.
	ContactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
		{Name: "github", Type: field.TypeString},
		{Name: "linkedin", Type: field.TypeString},
		{Name: "developper_contact", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// ContactsTable holds the schema information for the "contacts" table.
	ContactsTable = &schema.Table{
		Name:       "contacts",
		Columns:    ContactsColumns,
		PrimaryKey: []*schema.Column{ContactsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "contacts_developpers_contact",
				Columns: []*schema.Column{ContactsColumns[5]},

				RefColumns: []*schema.Column{DeveloppersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DeveloppersColumns holds the columns for the "developpers" table.
	DeveloppersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt},
		{Name: "school", Type: field.TypeString},
		{Name: "experience", Type: field.TypeInt},
	}
	// DeveloppersTable holds the schema information for the "developpers" table.
	DeveloppersTable = &schema.Table{
		Name:        "developpers",
		Columns:     DeveloppersColumns,
		PrimaryKey:  []*schema.Column{DeveloppersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContactsTable,
		DeveloppersTable,
	}
)

func init() {
	ContactsTable.ForeignKeys[0].RefTable = DeveloppersTable
}
