// Code generated by entc, DO NOT EDIT.

package developper

import (
	"SofwareGoDay3/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Age applies equality check predicate on the "age" field. It's identical to AgeEQ.
func Age(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAge), v))
	})
}

// School applies equality check predicate on the "school" field. It's identical to SchoolEQ.
func School(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSchool), v))
	})
}

// Experience applies equality check predicate on the "experience" field. It's identical to ExperienceEQ.
func Experience(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExperience), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Developper {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Developper(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Developper {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Developper(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// AgeEQ applies the EQ predicate on the "age" field.
func AgeEQ(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAge), v))
	})
}

// AgeNEQ applies the NEQ predicate on the "age" field.
func AgeNEQ(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAge), v))
	})
}

// AgeIn applies the In predicate on the "age" field.
func AgeIn(vs ...int) predicate.Developper {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Developper(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAge), v...))
	})
}

// AgeNotIn applies the NotIn predicate on the "age" field.
func AgeNotIn(vs ...int) predicate.Developper {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Developper(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAge), v...))
	})
}

// AgeGT applies the GT predicate on the "age" field.
func AgeGT(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAge), v))
	})
}

// AgeGTE applies the GTE predicate on the "age" field.
func AgeGTE(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAge), v))
	})
}

// AgeLT applies the LT predicate on the "age" field.
func AgeLT(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAge), v))
	})
}

// AgeLTE applies the LTE predicate on the "age" field.
func AgeLTE(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAge), v))
	})
}

// SchoolEQ applies the EQ predicate on the "school" field.
func SchoolEQ(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSchool), v))
	})
}

// SchoolNEQ applies the NEQ predicate on the "school" field.
func SchoolNEQ(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSchool), v))
	})
}

// SchoolIn applies the In predicate on the "school" field.
func SchoolIn(vs ...string) predicate.Developper {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Developper(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSchool), v...))
	})
}

// SchoolNotIn applies the NotIn predicate on the "school" field.
func SchoolNotIn(vs ...string) predicate.Developper {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Developper(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSchool), v...))
	})
}

// SchoolGT applies the GT predicate on the "school" field.
func SchoolGT(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSchool), v))
	})
}

// SchoolGTE applies the GTE predicate on the "school" field.
func SchoolGTE(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSchool), v))
	})
}

// SchoolLT applies the LT predicate on the "school" field.
func SchoolLT(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSchool), v))
	})
}

// SchoolLTE applies the LTE predicate on the "school" field.
func SchoolLTE(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSchool), v))
	})
}

// SchoolContains applies the Contains predicate on the "school" field.
func SchoolContains(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSchool), v))
	})
}

// SchoolHasPrefix applies the HasPrefix predicate on the "school" field.
func SchoolHasPrefix(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSchool), v))
	})
}

// SchoolHasSuffix applies the HasSuffix predicate on the "school" field.
func SchoolHasSuffix(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSchool), v))
	})
}

// SchoolEqualFold applies the EqualFold predicate on the "school" field.
func SchoolEqualFold(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSchool), v))
	})
}

// SchoolContainsFold applies the ContainsFold predicate on the "school" field.
func SchoolContainsFold(v string) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSchool), v))
	})
}

// ExperienceEQ applies the EQ predicate on the "experience" field.
func ExperienceEQ(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExperience), v))
	})
}

// ExperienceNEQ applies the NEQ predicate on the "experience" field.
func ExperienceNEQ(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldExperience), v))
	})
}

// ExperienceIn applies the In predicate on the "experience" field.
func ExperienceIn(vs ...int) predicate.Developper {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Developper(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldExperience), v...))
	})
}

// ExperienceNotIn applies the NotIn predicate on the "experience" field.
func ExperienceNotIn(vs ...int) predicate.Developper {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Developper(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldExperience), v...))
	})
}

// ExperienceGT applies the GT predicate on the "experience" field.
func ExperienceGT(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldExperience), v))
	})
}

// ExperienceGTE applies the GTE predicate on the "experience" field.
func ExperienceGTE(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldExperience), v))
	})
}

// ExperienceLT applies the LT predicate on the "experience" field.
func ExperienceLT(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldExperience), v))
	})
}

// ExperienceLTE applies the LTE predicate on the "experience" field.
func ExperienceLTE(v int) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldExperience), v))
	})
}

// HasContact applies the HasEdge predicate on the "contact" edge.
func HasContact() predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ContactTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ContactTable, ContactColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContactWith applies the HasEdge predicate on the "contact" edge with a given conditions (other predicates).
func HasContactWith(preds ...predicate.Contact) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ContactInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ContactTable, ContactColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCompetence applies the HasEdge predicate on the "competence" edge.
func HasCompetence() predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CompetenceTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CompetenceTable, CompetenceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompetenceWith applies the HasEdge predicate on the "competence" edge with a given conditions (other predicates).
func HasCompetenceWith(preds ...predicate.Competence) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CompetenceInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CompetenceTable, CompetenceColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Developper) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Developper) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Developper) predicate.Developper {
	return predicate.Developper(func(s *sql.Selector) {
		p(s.Not())
	})
}
