// Code generated by entc, DO NOT EDIT.

package ent

import (
	"SofwareGoDay3/ent/developper"
	"SofwareGoDay3/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DevelopperDelete is the builder for deleting a Developper entity.
type DevelopperDelete struct {
	config
	hooks    []Hook
	mutation *DevelopperMutation
}

// Where adds a new predicate to the DevelopperDelete builder.
func (dd *DevelopperDelete) Where(ps ...predicate.Developper) *DevelopperDelete {
	dd.mutation.predicates = append(dd.mutation.predicates, ps...)
	return dd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dd *DevelopperDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dd.hooks) == 0 {
		affected, err = dd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DevelopperMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dd.mutation = mutation
			affected, err = dd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dd.hooks) - 1; i >= 0; i-- {
			mut = dd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (dd *DevelopperDelete) ExecX(ctx context.Context) int {
	n, err := dd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dd *DevelopperDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: developper.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: developper.FieldID,
			},
		},
	}
	if ps := dd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, dd.driver, _spec)
}

// DevelopperDeleteOne is the builder for deleting a single Developper entity.
type DevelopperDeleteOne struct {
	dd *DevelopperDelete
}

// Exec executes the deletion query.
func (ddo *DevelopperDeleteOne) Exec(ctx context.Context) error {
	n, err := ddo.dd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{developper.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ddo *DevelopperDeleteOne) ExecX(ctx context.Context) {
	ddo.dd.ExecX(ctx)
}
