// Code generated by entc, DO NOT EDIT.

package ent

import (
	"SofwareGoDay3/ent/contact"
	"SofwareGoDay3/ent/developper"
	"SofwareGoDay3/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescID is the schema descriptor for id field.
	contactDescID := contactFields[0].Descriptor()
	// contact.IDValidator is a validator for the "id" field. It is called by the builders before save.
	contact.IDValidator = contactDescID.Validators[0].(func(int) error)
	developperFields := schema.Developper{}.Fields()
	_ = developperFields
	// developperDescAge is the schema descriptor for age field.
	developperDescAge := developperFields[2].Descriptor()
	// developper.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	developper.AgeValidator = developperDescAge.Validators[0].(func(int) error)
	// developperDescID is the schema descriptor for id field.
	developperDescID := developperFields[0].Descriptor()
	// developper.IDValidator is a validator for the "id" field. It is called by the builders before save.
	developper.IDValidator = developperDescID.Validators[0].(func(int) error)
}
