// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Competence is the predicate function for competence builders.
type Competence func(*sql.Selector)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// Developper is the predicate function for developper builders.
type Developper func(*sql.Selector)
